### ISSUE TITLE
Takes too much memory when we have to add like millions of links to the sitemap

### ISSUE THREAD

**Issue by macpatel** [RoumenDamianoff/laravel-sitemap#82]
It takes good amount of memory and time when we have like 1.5 Million links ,say from products and at the end of the loop we store it. which makes it take huge amount of memory and time before anything gets written to the disk.
```PHP
//Sample Code
$product_sitemap = \App::make("sitemap");
foreach ( $products in $products)
{
   $product_sitemap->add( route('site.product'), date('r'), 1.0, 'daily' );
}
$product_sitemap->store(''xml', 'sitemap-product'); //when the code is here all the links are in memory taking large amount of memory
```
There should be some mechanism so that when ever the links are >50000 , it should flush all the links to disk in a sitemap.

Thanks,
Mahesh

**Comment by RoumenDamianoff** [comment]
Hi, I found some issues that may cause too much memory to be used, If caching is enabled even when you generate sitemap to a file.. all generated sitemaps are still added to the cache (apc, memcache, redis) and on top of that after files are created all links are still in the memory.. this is clearly very wrong. 

Now this issues are fixed in the master branch, but there are still thinks to improve. I tested scenario with 1M links and it worked better. Still the links must be in the memory while sitemaps are generating, but after this memory should be flushed and cache not to be used at all.

**Comment by macpatel** [comment]
Thanks for your reply.

But don't you think that flushing the links to sitemap as the counts gets greater than 50K is much better approach ?

**Comment by RoumenDamianoff** [comment]
Yes, but this logic must be implemented in the controller, look at this [example](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Generate-BIG-sitemaps). Basically while you iterate your links you must count how many are added, when they hit 50000 you need to generate new sitemap, reset items array and your counter, add the new sitemap to the sitemaps array, and then continue to add more links and do the same until you are done. In the end you need to generate just one sitemapindex that holds all the other sitemaps. 

In this way you will never use to much memory to store millions of items, because on every 50000 you will reset them, you only may need to increase ```max_execution_time``` php directive and probably ```fastcgi_read_timeout``` time if you are using nginx.

**Comment by macpatel** [comment]
Thanks!
Yes, I am using similar kind of solution. Just thought that it could be built in within the package.

Anyways thanks for the example and taking time to answer my questions.
